### PR TITLE
usbip.exe - cancel and wait for async IO

### PR DESCRIPTION
**Pull request by koudis**
There is a problem with resource clean up.

We cannot wait with SleepEx because IO can get block.

### CODE REVIEW

**Comment by koudis** [comment]
After discussion with @cezanne and bartlomiejcieszkowski (in #120 ) it's no need to marge this PR now.

We will wait if the #120 helps with "hang after ctlr+c". (So no other user will have "hang after ctrl+c").

**Comment by cezanne** [comment]
@koudis: The current forwarder has several problems. One of them would be resolved by your PR. By the way, I committed a new branch([forwarder](https://github.com/cezanne/usbip-win/tree/forwarder)), which was inspired by your PR. It has been implemented with no SleepEx. I'll also review your PR but [forwarder branch](https://github.com/cezanne/usbip-win/tree/forwarder) would be a little more desirable.

**Comment by koudis** [comment]
@cezzane ou nice. I will look at thru this weekend :)

**Comment by koudis** [comment]
@cezanne sorry for delay. I tested master branch and it seem to work without problem. Thanks for your effort :).
I will close this PR.

**Comment by koudis** [comment]
@cezanne I test tha @bartlomiejcieszkowski branch with IRP Cacnel improvments.

Together with your changes it decreases latancy and many USB devices hosted on Linux and connected to Windws become really smooth (USb Mouse, serial controllers, ...). So the approach with events really boost USBIP vhci usablity :) .

**Pull request closed without merging**
