### PR TITLE
copy usb_vhci.cat to the TargetDir - quality of life

### PR DESCRIPTION
**Pull request by bartlomiejcieszkowski**
This adds post-build step that copies .cat file to the TargetDir - simplifies deployment as all the required files are at the same dir level

Inf2cat integration for the driver project, unfortunately has no flag to specify where to put catalog file, other solution would have been to add DriverPackage project which would produce it to the TargetDir

### CODE REVIEW

**Comment by koudis** [comment]
@bartlomiejcieszkowski ou thanks for that! :).

I wil ltest it thre this week together with #117

**Comment by bartlomiejcieszkowski** [comment]
@koudis i'm currently testing separate driver package, which would put the cat in the correct place

also i'm doing this as the inf2cat was taking a looooot of time, turns out it was doing so because the obj and tmh files in folder were scanned -_-"

**Comment by bartlomiejcieszkowski** [comment]
@koudis i've updated changeset - now it has separate package for usbip vhci, and the build is faster

**Comment by cezanne** [comment]
I'm going to close this PR whose idea was reflected by 4c99013a3be15ea5fcb0511aef6929d3dad69c55. Thanks @bartlomiejcieszkowski .

**Comment by bartlomiejcieszkowski** [comment]
#133 
i'm reopening, as the batch file has issues

**Comment by koudis** [comment]
solved in https://github.com/cezanne/usbip-win/pull/138

**Comment by bartlomiejcieszkowski** [comment]
closing as #138 is easier one

**Pull request closed without merging**
