### PR TITLE
fix DPC_WATCHDOG_VIOLATION - wrong context in irp cancel

### PR DESCRIPTION
**Pull request by bartlomiejcieszkowski**

### CODE REVIEW

**Comment by bartlomiejcieszkowski** [comment]
@cezanne i've introduced regression -_-" fixing

**Comment by koudis** [comment]
So maybe this can solve BSOD after detach?

**Comment by cezanne** [comment]
Is it possible? I have to investigate. 😅 @bartlomiejcieszkowski, please, let me have detailed information.
I remembered that the legacy code which I started this project was the same with this PR.

@koudis : 

> So maybe this can solve BSOD after detach?

@bartlomiejcieszkowski PR was recently merged but there had been the problems before. 
We have another latent pitfall.

https://github.com/cezanne/usbip-win/blob/0b675598cfe53843805c94372c9c45394cbbbc69/driver/vhci/usbreq.c#L138

**Comment by bartlomiejcieszkowski** [comment]
@cezanne dont worry, it was just a regression from my #120 , see details of this commit ;) 
I've switched in the #120 earlier to the DeviceExtension as you suggested, but havent tested it -_-" so as a result I was using pointer to the different context :)

**Pull request merged**
